### ISSUE TITLE
Выбор города и сохранение состояния

### ISSUE THREAD

**Issue by ghost** [web-standards-ru/calendar-app#2]
Привет! Отличная получилась штука. У меня есть пара предложений: добавить выбор города и сохранять страну и город в localstorage. Выглядеть это может примерно [вот так](http://g.recordit.co/9BO4WRQV1C.gif) (прошу прощения за курсор, но так почему-то работает прога для захвата видео). Там как раз показано, как работают селекты и как состояние сохраняется между перезагрузками страницы. 

Если это кажется полезным, могу сделать pr.

**Comment by dshved** [comment]
Привет. Я изначально делал выбор страны и выбор города, но при выборе страны остается не так много событий (за исключением России) и дополнительный фильтр мне показался излишним.
Если это повысит удобство использования, то почему нет)

**Comment by ghost** [comment]
@dshved https://github.com/web-standards-ru/calendar-app/pull/4
