### ISSUE TITLE
Выбор больше одного города/страны

### ISSUE THREAD

**Issue by miripiruni** [web-standards-ru/calendar-app#6]
Для Москвы и Петербурга кейс очевиден. Но, возможно, кто-то мотается между Берлином и Москвой. И тд.

**Comment by pepelsbey** [comment]
Или кто-то готов доехать до Москвы или Питера, особенно если речь идёт о конференциях.

**Comment by dshved** [comment]
@miripiruni @pepelsbey зацените https://build-wxjdrpdvnt.now.sh если норм, то смержу

**Comment by miripiruni** [comment]
@dshved выбираю страну A, добавляю города X и Y. Выбираю страну Б (с намерением добавить город Z) и вижу, что все города сбросились…

**Comment by dshved** [comment]
@miripiruni исправил. посмотри - https://build-zwyygebteo.now.sh/

**Comment by pepelsbey** [comment]
О, класс :) Теперь хорошо

**Comment by dshved** [comment]
#10
